### ISSUE TITLE
Script appears to run but doesn't result in a display

### ISSUE THREAD

**Issue by chrisnoy** [audiophonics/RaspDacMini#6] opened 2022-03-21 11:11 UTC
After waiting a long time for the oled version of volumio 3+ i have tried the gitub script.
The script seems to run ok with no errors but i dont get any display.
I can run rdmoled ok all else works but no display, can you help?
I downloaded Volumio 3.233 from volumio site, my setup is a kit from 2018 maybe the RPI is only 3 ...not sure.

After running sudo systemctl status oled as requested the following are the results:-
volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Welcome to Volumio for Raspberry Pi (5.10.92-v7+ armv7l)
volumio@volumio:~$ sudo systemctl status oled
● oled.service - OLED Display Service
   Loaded: loaded (/etc/systemd/system/oled.service; enabled; vendor preset: ena
   Active: failed (Result: exit-code) since Sun 2022-03-20 13:48:42 UTC; 21h ago
 Main PID: 794 (code=exited, status=1/FAILURE)

Mar 20 13:48:41 volumio systemd[1]: Started OLED Display Service.
Mar 20 13:48:41 volumio sudo[794]:     root : TTY=unknown ; PWD=/usr/local/etc/r
Mar 20 13:48:41 volumio sudo[794]: pam_unix(sudo:session): session opened for us
Mar 20 13:48:42 volumio sudo[794]: pam_unix(sudo:session): session closed for us
Mar 20 13:48:42 volumio systemd[1]: oled.service: Main process exited, code=exit
Mar 20 13:48:42 volumio systemd[1]: oled.service: Failed with result 'exit-code'
lines 1-11/11 (END)

**Comment by audiophonics** [comment] 2022-03-21 12:56
Hi, 

I do not remember any version of the device being sold with a Raspberry Pi version older than 3B+ so that is unlikely. 
However, I have been pushing a lot of files in a very short span of time so my guess would rather be I made a mistake somewhere. 

Let me investigate if I can reproduce this. Otherwise I will guide you to fix this.

**Comment by audiophonics** [comment] 2022-03-22 16:37
That was definitely me. I had left a rsync against my own timezone somewhere and some required files never had a chance to be copied where they belong.

I am still double checking but this should be fixed now, can you give it another try ? 

It should not be a problem to run the script again without reflashing the whole SD card. Worst thing that could happen is LIRC prompting 3-4 times for a "yes" at the end of the install before overwriting the remote configuration.

**Comment by chrisnoy** [comment] 2022-03-22 17:08
Hi there, tried it on the same config without flash and no display, ran the check again -see below.

Should i try on a freshly flashed card?

Volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Welcome to Volumio for Raspberry Pi (5.10.92-v7+ armv7l)
volumio@volumio:~$ sudo systemctl status oled
● oled.service - OLED Display Service
   Loaded: loaded (/etc/systemd/system/oled.service; enabled; vendor preset: ena
   Active: failed (Result: exit-code) since Tue 2022-03-22 17:03:42 UTC; 2min 42
  Process: 797 ExecStart=/usr/bin/sudo /usr/bin/node /usr/local/etc/raspdacminio
 Main PID: 797 (code=exited, status=1/FAILURE)

Mar 22 17:03:41 volumio systemd[1]: Started OLED Display Service.
Mar 22 17:03:41 volumio sudo[797]:     root : TTY=unknown ; PWD=/usr/local/etc/r
Mar 22 17:03:41 volumio sudo[797]: pam_unix(sudo:session): session opened for us
Mar 22 17:03:42 volumio sudo[797]: pam_unix(sudo:session): session closed for us
Mar 22 17:03:42 volumio systemd[1]: oled.service: Main process exited, code=exit
Mar 22 17:03:42 volumio systemd[1]: oled.service: Failed with result 'exit-code'
lines 1-12/12 (END)


Volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Welcome to Volumio for Raspberry Pi (5.10.92-v7+ armv7l)
volumio@volumio:~$ sudo systemctl status oled
● oled.service - OLED Display Service
   Loaded: loaded (/etc/systemd/system/oled.service; enabled; vendor preset: ena
   Active: failed (Result: exit-code) since Tue 2022-03-22 17:03:42 UTC; 2min 42
  Process: 797 ExecStart=/usr/bin/sudo /usr/bin/node /usr/local/etc/raspdacminio
 Main PID: 797 (code=exited, status=1/FAILURE)

Mar 22 17:03:41 volumio systemd[1]: Started OLED Display Service.
Mar 22 17:03:41 volumio sudo[797]:     root : TTY=unknown ; PWD=/usr/local/etc/r
Mar 22 17:03:41 volumio sudo[797]: pam_unix(sudo:session): session opened for us
Mar 22 17:03:42 volumio sudo[797]: pam_unix(sudo:session): session closed for us
Mar 22 17:03:42 volumio systemd[1]: oled.service: Main process exited, code=exit
Mar 22 17:03:42 volumio systemd[1]: oled.service: Failed with result 'exit-code'
lines 1-12/12 (END)

**Comment by chrisnoy** [comment] 2022-03-22 17:46
Hi there,

Success, I had to re flash the card then it worked fine, thanks for all your hard work on this.

**Comment by audiophonics** [comment] 2022-03-23 08:57
Oh. I should have told you to remove the previous installation files beforehand. That was probably the reason it failed a second time. 
Now that I have this working, I will document the compiling process so all this should hold with minor maintenance until a new major version of Volumio is released.

**Closed as completed by audiophonics** 2022-03-23 08:57 UTC
